# Relabeled Test No Blur

Relabel test set items

In [13]:
# Packages
import pandas as pd

## Load data

In [14]:
# Load '../../../Data/resized_cars_annos.xlsx'
resized_cars_annos = pd.read_excel('../../../Data/resized_cars_annos.xlsx')
resized_cars_annos

,Class,old_class_name,orig_width,orig_height,test_80_20,orig_res_file_path,parameter_testing_destination_file_name,blurred_destination_file_name,no_blur_destination_file_name
0,SUV,AM General Hummer SUV 2000,800,600,0,~/Box/INFO 290T Project/Intermediate Data/Sele...,SUV_train_orig_test_01117_resized.jpg,SUV_train_orig_test_01117_resized_blurred.jpg,SUV_train_orig_test_01117_resized_no_blur.jpg
1,SUV,AM General Hummer SUV 2000,800,520,0,~/Box/INFO 290T Project/Intermediate Data/Sele...,SUV_train_orig_test_01518_resized.jpg,SUV_train_orig_test_01518_resized_blurred.jpg,SUV_train_orig_test_01518_resized_no_blur.jpg
2,SUV,AM General Hummer SUV 2000,500,353,0,~/Box/INFO 290T Project/Intermediate Data/Sele...,SUV_train_orig_test_01538_resized.jpg,SUV_train_orig_test_01538_resized_blurred.jpg,SUV_train_orig_test_01538_resized_no_blur.jpg
3,SUV,AM General Hummer SUV 2000,786,491,0,~/Box/INFO 290T Project/Intermediate Data/Sele...,SUV_train_orig_test_01802_resized.jpg,SUV_train_orig_test_01802_resized_blurred.jpg,SUV_train_orig_test_01802_resized_no_blur.jpg
4,SUV,AM General Hummer SUV 2000,800,580,0,~/Box/INFO 290T Project/Intermediate Data/Sele...,SUV_train_orig_test_01887_resized.jpg,SUV_train_orig_test_01887_resized_blurred.jpg,SUV_train_orig_test_01887_resized_no_blur.jpg
...,...,...,...,...,...,...,...,...,...
8247,Convertible,smart fortwo Convertible 2012,630,420,0,~/Box/INFO 290T Project/Intermediate Data/Sele...,Convertible_train_orig_train_07500_resized.jpg,Convertible_train_orig_train_07500_resized_blu...,Convertible_train_orig_train_07500_resized_no_...
8248,Convertible,smart fortwo Convertible 2012,400,300,0,~/Box/INFO 290T Project/Intermediate Data/Sele...,Convertible_train_orig_train_07594_resized.jpg,Convertible_train_orig_train_07594_resized_blu...,Convertible_train_orig_train_07594_resized_no_...
8249,Convertible,smart fortwo Convertible 2012,1024,683,0,~/Box/INFO 290T Project/Intermediate Data/Sele...,Convertible_train_orig_train_07846_resized.jpg,Convertible_train_orig_train_07846_resized_blu...,Convertible_train_orig_train_07846_resized_no_...
8250,Convertible,smart fortwo Convertible 2012,500,272,0,~/Box/INFO 290T Project/Intermediate Data/Sele...,Convertible_train_orig_train_07895_resized.jpg,Convertible_train_orig_train_07895_resized_blu...,Convertible_train_orig_train_07895_resized_no_...
8251,Convertible,smart fortwo Convertible 2012,800,600,0,~/Box/INFO 290T Project/Intermediate Data/Sele...,Convertible_train_orig_train_08141_resized.jpg,Convertible_train_orig_train_08141_resized_blu...,Convertible_train_orig_train_08141_resized_no_...

In [15]:
# Limit to test
resized_cars_annos_test = resized_cars_annos[resized_cars_annos['test_80_20'] == 1]
resized_cars_annos_test

,Class,old_class_name,orig_width,orig_height,test_80_20,orig_res_file_path,parameter_testing_destination_file_name,blurred_destination_file_name,no_blur_destination_file_name
6,SUV,AM General Hummer SUV 2000,640,480,1,~/Box/INFO 290T Project/Intermediate Data/Sele...,SUV_test_orig_test_02205_resized.jpg,SUV_test_orig_test_02205_resized_blurred.jpg,SUV_test_orig_test_02205_resized_no_blur.jpg
7,SUV,AM General Hummer SUV 2000,750,469,1,~/Box/INFO 290T Project/Intermediate Data/Sele...,SUV_test_orig_test_02835_resized.jpg,SUV_test_orig_test_02835_resized_blurred.jpg,SUV_test_orig_test_02835_resized_no_blur.jpg
8,SUV,AM General Hummer SUV 2000,490,325,1,~/Box/INFO 290T Project/Intermediate Data/Sele...,SUV_test_orig_test_03073_resized.jpg,SUV_test_orig_test_03073_resized_blurred.jpg,SUV_test_orig_test_03073_resized_no_blur.jpg
17,SUV,AM General Hummer SUV 2000,490,368,1,~/Box/INFO 290T Project/Intermediate Data/Sele...,SUV_test_orig_test_07530_resized.jpg,SUV_test_orig_test_07530_resized_blurred.jpg,SUV_test_orig_test_07530_resized_no_blur.jpg
22,SUV,AM General Hummer SUV 2000,500,375,1,~/Box/INFO 290T Project/Intermediate Data/Sele...,SUV_test_orig_train_01952_resized.jpg,SUV_test_orig_train_01952_resized_blurred.jpg,SUV_test_orig_train_01952_resized_no_blur.jpg
...,...,...,...,...,...,...,...,...,...
8225,Convertible,smart fortwo Convertible 2012,620,388,1,~/Box/INFO 290T Project/Intermediate Data/Sele...,Convertible_test_orig_train_00222_resized.jpg,Convertible_test_orig_train_00222_resized_blur...,Convertible_test_orig_train_00222_resized_no_b...
8229,Convertible,smart fortwo Convertible 2012,480,360,1,~/Box/INFO 290T Project/Intermediate Data/Sele...,Convertible_test_orig_train_02844_resized.jpg,Convertible_test_orig_train_02844_resized_blur...,Convertible_test_orig_train_02844_resized_no_b...
8230,Convertible,smart fortwo Convertible 2012,1024,768,1,~/Box/INFO 290T Project/Intermediate Data/Sele...,Convertible_test_orig_train_02961_resized.jpg,Convertible_test_orig_train_02961_resized_blur...,Convertible_test_orig_train_02961_resized_no_b...
8231,Convertible,smart fortwo Convertible 2012,500,315,1,~/Box/INFO 290T Project/Intermediate Data/Sele...,Convertible_test_orig_train_03276_resized.jpg,Convertible_test_orig_train_03276_resized_blur...,Convertible_test_orig_train_03276_resized_no_b...
8232,Convertible,smart fortwo Convertible 2012,450,329,1,~/Box/INFO 290T Project/Intermediate Data/Sele...,Convertible_test_orig_train_03728_resized.jpg,Convertible_test_orig_train_03728_resized_blur...,Convertible_test_orig_train_03728_resized_no_b...

In [16]:
# Load new labels in '../../../Data/Relabeled_Test_No_Blur/default.txt'
new_labels = pd.read_csv('../../../Data/Relabeled_Test_No_Blur/default.txt', sep=" ", header=None)
new_labels.columns = ['filename', 'label']
# In filename, remove 'No Blur/'
new_labels['filename'] = new_labels['filename'].str.replace('No Blur/', '')
# print filename for first row
print(new_labels['filename'][0])
new_labels

Convertible_test_orig_test_00023_resized_no_blur.jpg

                                               filename  label
0     Convertible_test_orig_test_00023_resized_no_bl...      2
1     Convertible_test_orig_test_00096_resized_no_bl...      2
2     Convertible_test_orig_test_00107_resized_no_bl...      2
3     Convertible_test_orig_test_00135_resized_no_bl...      2
4     Convertible_test_orig_test_00147_resized_no_bl...      2
...                                                 ...    ...
1651    Sedan_test_orig_train_08026_resized_no_blur.jpg      5
1652    Sedan_test_orig_train_08043_resized_no_blur.jpg      3
1653    Sedan_test_orig_train_08046_resized_no_blur.jpg      3
1654    Sedan_test_orig_train_08098_resized_no_blur.jpg      3
1655    Sedan_test_orig_train_08113_resized_no_blur.jpg      3

[1656 rows x 2 columns]

In [17]:
# Load key for labels '../../../Data/Relabeled_Test_No_Blur/synsets.txt'
# First open text file and replace 'Clearly None of the 4' with 'Clearly_None_of_the_4'
with open('../../../Data/Relabeled_Test_No_Blur/synsets.txt', 'r') as file:
    filedata = file.read()
print(filedata)
# Convert each line into a list item, enumerate
class_list = filedata.split('\n')
# Remove empty items
class_list = list(filter(None, class_list))
print(class_list)
# Create dataframe of class_list with items as 'New Class' and a row number column called label
class_list_df = pd.DataFrame(class_list, columns=['New Class'])
class_list_df['label'] = class_list_df.index
class_list_df

SUV
Pickup
Convertible
Sedan
Clearly None of the 4
Ambiguous

['SUV', 'Pickup', 'Convertible', 'Sedan', 'Clearly None of the 4', 'Ambiguous']

               New Class  label
0                    SUV      0
1                 Pickup      1
2            Convertible      2
3                  Sedan      3
4  Clearly None of the 4      4
5              Ambiguous      5

# Merge data

In [18]:
merged = pd.merge(new_labels, class_list_df, left_on='label', right_on='label', how='left')
merged

                                               filename  label    New Class
0     Convertible_test_orig_test_00023_resized_no_bl...      2  Convertible
1     Convertible_test_orig_test_00096_resized_no_bl...      2  Convertible
2     Convertible_test_orig_test_00107_resized_no_bl...      2  Convertible
3     Convertible_test_orig_test_00135_resized_no_bl...      2  Convertible
4     Convertible_test_orig_test_00147_resized_no_bl...      2  Convertible
...                                                 ...    ...          ...
1651    Sedan_test_orig_train_08026_resized_no_blur.jpg      5    Ambiguous
1652    Sedan_test_orig_train_08043_resized_no_blur.jpg      3        Sedan
1653    Sedan_test_orig_train_08046_resized_no_blur.jpg      3        Sedan
1654    Sedan_test_orig_train_08098_resized_no_blur.jpg      3        Sedan
1655    Sedan_test_orig_train_08113_resized_no_blur.jpg      3        Sedan

[1656 rows x 3 columns]

In [19]:
# Old Class as filename up to first underscore
merged['Old Class'] = merged['filename'].str.split('_').str[0]
merged

,filename,label,New Class,Old Class
0,Convertible_test_orig_test_00023_resized_no_bl...,2,Convertible,Convertible
1,Convertible_test_orig_test_00096_resized_no_bl...,2,Convertible,Convertible
2,Convertible_test_orig_test_00107_resized_no_bl...,2,Convertible,Convertible
3,Convertible_test_orig_test_00135_resized_no_bl...,2,Convertible,Convertible
4,Convertible_test_orig_test_00147_resized_no_bl...,2,Convertible,Convertible
...,...,...,...,...
1651,Sedan_test_orig_train_08026_resized_no_blur.jpg,5,Ambiguous,Sedan
1652,Sedan_test_orig_train_08043_resized_no_blur.jpg,3,Sedan,Sedan
1653,Sedan_test_orig_train_08046_resized_no_blur.jpg,3,Sedan,Sedan
1654,Sedan_test_orig_train_08098_resized_no_blur.jpg,3,Sedan,Sedan
1655,Sedan_test_orig_train_08113_resized_no_blur.jpg,3,Sedan,Sedan

## Create Harmonized File Name

In [20]:
def create_harmonized_filename(file_path):
    '''
    Strip Blur vs. No Blur and other data from file path.
    '''
    # Split path by '/' and take last element
    harmonized_filename = file_path.split('/')[-1]
    # Remove _no_blur and _blurred from file name
    harmonized_filename = harmonized_filename.replace('_no_blur', '')
    harmonized_filename = harmonized_filename.replace('_blurred', '')
    # Return harmonized file name
    return harmonized_filename

In [21]:
# Use funciton on 'filename' column
merged['harmonized_filename'] = merged['filename'].apply(create_harmonized_filename)
merged

,filename,label,New Class,Old Class,harmonized_filename
0,Convertible_test_orig_test_00023_resized_no_bl...,2,Convertible,Convertible,Convertible_test_orig_test_00023_resized.jpg
1,Convertible_test_orig_test_00096_resized_no_bl...,2,Convertible,Convertible,Convertible_test_orig_test_00096_resized.jpg
2,Convertible_test_orig_test_00107_resized_no_bl...,2,Convertible,Convertible,Convertible_test_orig_test_00107_resized.jpg
3,Convertible_test_orig_test_00135_resized_no_bl...,2,Convertible,Convertible,Convertible_test_orig_test_00135_resized.jpg
4,Convertible_test_orig_test_00147_resized_no_bl...,2,Convertible,Convertible,Convertible_test_orig_test_00147_resized.jpg
...,...,...,...,...,...
1651,Sedan_test_orig_train_08026_resized_no_blur.jpg,5,Ambiguous,Sedan,Sedan_test_orig_train_08026_resized.jpg
1652,Sedan_test_orig_train_08043_resized_no_blur.jpg,3,Sedan,Sedan,Sedan_test_orig_train_08043_resized.jpg
1653,Sedan_test_orig_train_08046_resized_no_blur.jpg,3,Sedan,Sedan,Sedan_test_orig_train_08046_resized.jpg
1654,Sedan_test_orig_train_08098_resized_no_blur.jpg,3,Sedan,Sedan,Sedan_test_orig_train_08098_resized.jpg
1655,Sedan_test_orig_train_08113_resized_no_blur.jpg,3,Sedan,Sedan,Sedan_test_orig_train_08113_resized.jpg

## Basic Analytics

In [22]:
# Share of times Old Class is not equal to New Class
print('share of times Old Class is not equal to New Class')
print(len(merged[merged['Old Class'] != merged['New Class']]) / len(merged))

share of times Old Class is not equal to New Class
0.1105072463768116

In [23]:
print('share of times ambiguous')
print(len(merged[merged['New Class'] == 'Ambiguous']) / len(merged))

share of times ambiguous
0.09722222222222222

## Save Data

In [24]:
# Save file '../../../Data/Relabeled_Test_No_Blur/relabeled_test_no_blur_old_and_new_labels.xlsx'
merged.to_excel('../../../Data/Relabeled_Test_No_Blur/relabeled_test_no_blur_old_and_new_labels.xlsx', index=False)