# Create Selected Images

Limit classes, get rid of low resolution images

Create new train-test split in folders

Create new, filtered file with class labels

In [14]:
# Packages
import pandas as pd
import openpyxl
import os
import shutil
import time
import numpy as np

In [15]:
# Load "~/Box/INFO 290T Project/Intermediate Data/cars_annos.xlsx"
cars_annos = pd.read_excel("~/Box/INFO 290T Project/Intermediate Data/cars_annos.xlsx")
cars_annos

,Class,filename,x1,y1,x2,y2,old_class,test,old_class_name,im_path,width,height,num_pixels,test_80_20
0,SUV,00076.jpg,11,13,84,60,1,1,AM General Hummer SUV 2000,/Box/INFO 290T Project/Raw Data/Stanford Car D...,96,64,6144,0
1,SUV,00457.jpg,31,20,226,119,1,1,AM General Hummer SUV 2000,/Box/INFO 290T Project/Raw Data/Stanford Car D...,250,144,36000,0
2,SUV,00684.jpg,111,54,365,190,1,1,AM General Hummer SUV 2000,/Box/INFO 290T Project/Raw Data/Stanford Car D...,373,216,80568,0
3,SUV,01117.jpg,45,39,729,414,1,1,AM General Hummer SUV 2000,/Box/INFO 290T Project/Raw Data/Stanford Car D...,800,600,480000,0
4,SUV,01167.jpg,14,16,268,169,1,1,AM General Hummer SUV 2000,/Box/INFO 290T Project/Raw Data/Stanford Car D...,278,182,50596,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16180,Convertible,07537.jpg,47,65,249,180,196,0,smart fortwo Convertible 2012,/Box/INFO 290T Project/Raw Data/Stanford Car D...,262,193,50566,0
16181,Convertible,07594.jpg,29,34,381,273,196,0,smart fortwo Convertible 2012,/Box/INFO 290T Project/Raw Data/Stanford Car D...,400,300,120000,0
16182,Convertible,07846.jpg,78,289,669,633,196,0,smart fortwo Convertible 2012,/Box/INFO 290T Project/Raw Data/Stanford Car D...,1024,683,699392,0
16183,Convertible,07895.jpg,31,6,494,272,196,0,smart fortwo Convertible 2012,/Box/INFO 290T Project/Raw Data/Stanford Car D...,500,272,136000,0
16184,Convertible,08141.jpg,138,150,706,523,196,0,smart fortwo Convertible 2012,/Box/INFO 290T Project/Raw Data/Stanford Car D...,800,600,480000,0

## Limit Images

In [16]:
limited_cars_annos = cars_annos.query('Class in ["SUV", "Sedan", "Convertible", "Pickup"] and width > 350 and height > 200').reset_index(drop=True)
print(limited_cars_annos['Class'].value_counts())
print(limited_cars_annos[['width', 'height']].describe())
limited_cars_annos

Class
Sedan          3516
SUV            2472
Convertible    1556
Pickup          897
Name: count, dtype: int64
             width       height
count  8441.000000  8441.000000
mean    804.102121   555.084469
std     446.763539   314.669960
min     353.000000   201.000000
25%     569.000000   365.000000
50%     640.000000   480.000000
75%    1021.000000   640.000000
max    7800.000000  5400.000000

,Class,filename,x1,y1,x2,y2,old_class,test,old_class_name,im_path,width,height,num_pixels,test_80_20
0,SUV,00684.jpg,111,54,365,190,1,1,AM General Hummer SUV 2000,/Box/INFO 290T Project/Raw Data/Stanford Car D...,373,216,80568,0
1,SUV,01117.jpg,45,39,729,414,1,1,AM General Hummer SUV 2000,/Box/INFO 290T Project/Raw Data/Stanford Car D...,800,600,480000,0
2,SUV,01518.jpg,26,62,763,504,1,1,AM General Hummer SUV 2000,/Box/INFO 290T Project/Raw Data/Stanford Car D...,800,520,416000,0
3,SUV,01538.jpg,32,69,487,316,1,1,AM General Hummer SUV 2000,/Box/INFO 290T Project/Raw Data/Stanford Car D...,500,353,176500,0
4,SUV,01802.jpg,46,115,623,469,1,1,AM General Hummer SUV 2000,/Box/INFO 290T Project/Raw Data/Stanford Car D...,786,491,385926,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8436,Convertible,07500.jpg,20,27,613,413,196,0,smart fortwo Convertible 2012,/Box/INFO 290T Project/Raw Data/Stanford Car D...,630,420,264600,0
8437,Convertible,07594.jpg,29,34,381,273,196,0,smart fortwo Convertible 2012,/Box/INFO 290T Project/Raw Data/Stanford Car D...,400,300,120000,0
8438,Convertible,07846.jpg,78,289,669,633,196,0,smart fortwo Convertible 2012,/Box/INFO 290T Project/Raw Data/Stanford Car D...,1024,683,699392,0
8439,Convertible,07895.jpg,31,6,494,272,196,0,smart fortwo Convertible 2012,/Box/INFO 290T Project/Raw Data/Stanford Car D...,500,272,136000,0
8440,Convertible,08141.jpg,138,150,706,523,196,0,smart fortwo Convertible 2012,/Box/INFO 290T Project/Raw Data/Stanford Car D...,800,600,480000,0

In [17]:
# Variable for originally train or test
limited_cars_annos['orig_train_or_test'] = np.where(limited_cars_annos['test'] == 0, 'train', 'test')
limited_cars_annos['orig_train_or_test'].value_counts()

orig_train_or_test
train    4259
test     4182
Name: count, dtype: int64

## Create New Train-Test Split in Folders

In [18]:
# Print first value of im_path
print(limited_cars_annos['im_path'][0])

/Box/INFO 290T Project/Raw Data/Stanford Car Dataset/cars_test/cars_test/00684.jpg

In [19]:
# Iterate over rows
# Copy image to "~/Box\INFO 290T Project\Intermediate Data\Selected Images\train" (or test) with Class and train (or test) appended to front of file name
# List of new file paths
new_file_paths = []
new_file_names = []
# Clear directories
start = time.time()
shutil.rmtree(os.path.expanduser('~') + "/Box/INFO 290T Project/Intermediate Data/Selected Images/train")
shutil.rmtree(os.path.expanduser('~') + "/Box/INFO 290T Project/Intermediate Data/Selected Images/test")
os.makedirs(os.path.expanduser('~') + "/Box/INFO 290T Project/Intermediate Data/Selected Images/train")
os.makedirs(os.path.expanduser('~') + "/Box/INFO 290T Project/Intermediate Data/Selected Images/test")
end = time.time()
print("Time to clear directories in min: ", (end - start) / 60)
# start timer
start = time.time()
for start_im_path, start_filename, test_80_20_val, Class, orig_train_or_test in limited_cars_annos[['im_path', 'filename', 'test_80_20', 'Class', 'orig_train_or_test']].itertuples(index=False):
    if test_80_20_val == 0:
        source = os.path.expanduser('~') + start_im_path
        new_file_name = Class + "_train_orig_" + orig_train_or_test + "_" + start_filename
        destination = os.path.expanduser('~') + "/Box/INFO 290T Project/Intermediate Data/Selected Images/train/" + new_file_name
        shutil.copy(source, destination)
        new_file_names.append(new_file_name)
        new_file_paths.append("~" + "/Box/INFO 290T Project/Intermediate Data/Selected Images/train/" + new_file_name)
    else:
        source = os.path.expanduser('~') + start_im_path
        new_file_name = Class + "_test_orig_" + orig_train_or_test + "_" + start_filename
        destination = os.path.expanduser('~') + "/Box/INFO 290T Project/Intermediate Data/Selected Images/test/" + new_file_name
        shutil.copy(source, destination)
        new_file_names.append(new_file_name)
        new_file_paths.append("~" + "/Box/INFO 290T Project/Intermediate Data/Selected Images/test/" + new_file_name)
# end timer
end = time.time()
print("Time to copy images in min: ", (end - start) / 60)

Time to clear directories in min:  0.4129888852437337
Time to copy images in min:  3.093318498134613

## Updated Excel file

In [20]:
# Add new file paths to limited_cars_annos
limited_cars_annos['new_file_path'] = new_file_paths
# Add new file names to limited_cars_annos
limited_cars_annos['new_file_name'] = new_file_names
# Delete test, im_path, filename columns
limited_cars_annos = limited_cars_annos.drop(columns=['test', 'im_path', 'filename'])
# Save to "~/Box/INFO 290T Project/Intermediate Data/selected_cars_annos.xlsx"
limited_cars_annos.to_excel("~/Box/INFO 290T Project/Intermediate Data/selected_cars_annos.xlsx", index=False)